### ISSUE TITLE
Non-Multimedia Content?

### ISSUE THREAD

**Issue by dwasyl** [trvswgnr/bs5-lightbox#10]
Can this lightbox be used to display a `<div></div>` with a small table of data, or only multimedia content? Seemingly some tweaks would be required, but I wasn't sure where.

**Comment by trvswgnr** [comment]
Currently you can't directly add HTML into the lightbox, but you could add your content to another page and then create a lightbox with that url as seen here: https://trvswgnr.github.io/bs5-lightbox/#remote-content

**Comment by dwasyl** [comment]
That makes sense, I was just hoping to avoid the extra http call and  add it directly or have an inline div elsewhere on the page.

**Comment by trvswgnr** [comment]
@dwasyl I agree that would be useful. I’ll definitely consider it in the next release.

**Comment by trvswgnr** [comment]
@dwasyl I added this in release [v.1.8.0](https://github.com/trvswgnr/bs5-lightbox/releases/tag/v1.8.0). You can see an example here: https://trvswgnr.github.io/bs5-lightbox/#custom-html

**Comment by dwasyl** [comment]
@trvswgnr amazing! That's great, thanks!
