### ISSUE TITLE
Gallery popup sliding in instead of just changing the image

### ISSUE THREAD

**Issue by theDaveB** [trvswgnr/bs5-lightbox#21]
On the latest version of Bootstrap 5.2.0, when scrolling through a gallery of images, each image slides the whole carousel in from the whatever side you click.

If I change to the version on your demo page (5.0.2) then it works exactly like your demo.

Am new to all this so hope am doing it right by reporting it here.

**Comment by trvswgnr** [comment]
@theDaveB the library currently supports up to Bootstrap 5.1.3, but I am already looking at the changes made in Bootstrap 5.2 and I will hopefully be able to push a fix soon. Thanks!

**Comment by trvswgnr** [comment]
fixed with PR #24
