### ISSUE TITLE
How to use without npm?

### ISSUE THREAD

**Issue by paulo-coutinho** [trvswgnr/bs5-lightbox#3]
Hi,

How to use without npm?

Direct in HTML on head.

Thanks.

**Comment by trvswgnr** [comment]
You can add the script tag with the CDN package right after the Bootstrap JS:
```html
<script src="https://cdn.jsdelivr.net/npm/bs5-lightbox@1.7.7/dist/index.bundle.min.js"></script>
```

See the examples [in the documentation.](https://trvswgnr.github.io/bs5-lightbox/)
