### ISSUE TITLE
bootstrap error with angular 14

### ISSUE THREAD

**Issue by emrahtepe** [trvswgnr/bs5-lightbox#33]
Hi,
I get this error. can you give me a tip what to do?
![image](https://user-images.githubusercontent.com/87071212/193361816-4b48a009-fc20-4fd8-afdf-1593ebcee742.png)

bootstrap already installed
![image](https://user-images.githubusercontent.com/87071212/193362163-601a4054-3a1f-4631-89cf-77270342aa33.png)

**Comment by trvswgnr** [comment]
I think you would need to do something like `typeof bootstrap.Modal.Options`?

**Comment by emrahtepe** [comment]
It throws TS2503: Cannot find namespace 'bootstrap'. error when build.

I have found a bypass. I added `"skipLibCheck": true` to tsconfig. json file. It builds without error now.
