### ISSUE TITLE
Using google drive images Bootstrap 5 and Lightbox 403 error

### ISSUE THREAD

**Issue by omdawe** [trvswgnr/bs5-lightbox#34]
So im using google drive images and with the standard image link the image dont load and gives a 403 error.

```
<a href="https://drive.google.com/thumbnail?id=1n7l1sFnytkPLXF5SBjvaAs6srSjHgvWO&sz=w1080" data-toggle="lightbox" data-gallery="gallery" class="col-sm-4 img-fluid">
<img src="https://drive.google.com/thumbnail?id=1n7l1sFnytkPLXF5SBjvaAs6srSjHgvWO&sz=w300" class="img-fluid"></a>

```
A "fix" is to change the google link to https://lh3.googleusercontent.com/d/1n7l1sFnytkPLXF5SBjvaAs6srSjHgvWO=w1080 as its not the standard API from google drive so this "fix" might just be working temporarily

But the image dont get the img-fluid class so the full image is not fitted in to the lightbox.

**Comment by trvswgnr** [comment]
Hi @omdawe have you tried adding `data-type="image"` to the trigger element?

**Comment by omdawe** [comment]
ooo SHIT!! No i did not try that.. THAT WORKED! Thanks man!

**Comment by trvswgnr** [comment]
@omdawe lol no problem!
