### ISSUE TITLE
Standalone example bundle would be great

### ISSUE THREAD

**Issue by eduardomart** [trvswgnr/bs5-lightbox#39]
I am having a hard time understanding how to implement the options, could you please provide a standalone example, where I can look at the full code of a page that uses your plugin?

I looked at the code in your website but it didn't clarify things either.

Thank you.

**Comment by trvswgnr** [comment]
Hi @eduardomart did you check out the example at https://trvswgnr.github.io/bs5-lightbox/#options? What would you like to see exactly? I have been thinking about providing standalone examples with CodePen but that's not something I have the bandwidth for at the moment.

**Comment by trvswgnr** [comment]
Checking in on this—did you find what you were looking for?

**Comment by eduardomart** [comment]
Sorry, I couldn't figure it out how to use your script so I went ahead and used [fslightbox](https://fslightbox.com) instead.
