### ISSUE TITLE
Uncaught TypeError: s is undefined

### ISSUE THREAD

**Issue by iteidrm** [trvswgnr/bs5-lightbox#55]
Hello,

I'm trying to include this script into a CMS Template (head or end of body) via the <script>-Tag. The browser console however shows the following error message:

`Uncaught TypeError: s is undefined
    <anonymous> index.js:10
    <anonymous> index.bundle.min.js:5`

Bootstrap 5.1.3 incl. modal and carousel are loaded (as far as I can tell).

**Comment by trvswgnr** [comment]
@iteidrm are you certain that it is being loaded after Bootstrap?

**Comment by iteidrm** [comment]
Hello @trvswgnr,

thanks for your reply. Both the CSS and JavaScript files seem to be loaded (visible in the pages source view) and if I type window.bootstrap into the console windows, I get the following output:

`window.bootstrap

Object { Collapse: class Collapse }`

I've now added _defer_ to the script tag to make sure it gets loaded last which indeed solved the problem.
