### ISSUE TITLE
Not loading on Bootstrap 5.3.2

### ISSUE THREAD

**Issue by MrSATAN1999** [trvswgnr/bs5-lightbox#76]
Hi !
I'm having difficulties setting it up on Bootstrap 5.3.2.

I'm trying to load latest version from CDN : 
`<script src="https://cdn.jsdelivr.net/npm/bs5-lightbox@1.8.3/dist/index.bundle.min.js"></script>`

Of course it's placed AFTER Bootstrap's JS : 
`<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>`

And I'm trying to call it from any page that way : 
`<a href="photos/galeries/63ab4837330da.jpg" style="background:url('photos/galeries/63ab4837330da.jpg') center;" class="col-md m-1 btn btn-secondary btn-zoom img-1" data-toggle="lightbox"></a>`
The pictures opens in a _blank page.

I also tried to change `data-toggle` with `data-bs-toggle` as this is the new Bootstrap way but nothing seems to be working.

Am I missing something here ? Thanks.

**Comment by MrSATAN1999** [comment]
Hi !
I figured where the preblem occured. I needed the script to be loaded at the end of <body>.
Might be a good idea to give this info in the installation direction.
Thanks for the plugin !

**Comment by MrSATAN1999** [comment]
Hi !
I figured where the preblem occured. I needed the script to be loaded at the end of <body>.
Might be a good idea to give this info in the installation direction.
Thanks for the plugin !

**Comment by TheCrowned** [comment]
Thanks, helped me too!
