### ISSUE TITLE
Feature Request: Constrain image to original dimensions

### ISSUE THREAD

**Issue by cocowalla** [trvswgnr/bs5-lightbox#9]
With low-res images, I'd like to be able to prevent the image from being displayed any larger than the original resolution.

Thanks for your consideration, and for this library 🙏

**Comment by trvswgnr** [comment]
I think this could be done relatively easy, I'll implement this soon in a future version.

**Comment by trvswgnr** [comment]
PR #16 includes this and will be available in the next version.

**Comment by trvswgnr** [comment]
@cocowalla this has been included in [v1.8.1](https://github.com/trvswgnr/bs5-lightbox/releases/tag/v1.8.1)
